[tool.pyright]
include = ["app", "scripts", "tests", "run_desktop.py", "start.py"]
exclude = ["**/__pycache__"]
venvPath = "."
venv = ".venv"
reportMissingImports = true
reportUnusedImport = true

[tool.bandit]
# B101: assert_used (разрешено в тестах)
# B404: import_subprocess (разрешено в скриптах)
# B603: subprocess_without_shell_equals_true (разрешено в скриптах)
skips = ["B101", "B404", "B603"]