services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ../app:/app 
      - ../tests:/tests
      - ../quest-generator/models:/models
    environment:
      - LOCAL_MODEL_PATH=/models