services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ../app:/app 
      - ../tests:/tests
    # command: ["sleep", "3600"]